development:
  config:
    http_timeout: 45
  accounts:
    -
      id: pm_test
      account_id: 9082732
      pass_phrase: polopuikiu123
      secret_key: C9TzRxB5gt20Z3OofLcKmDpnJ
      deposit_account:
        usd: U5329529
      withdrawal_account:
        usd: U6260277