development:
  config:
    http_timeout: 45
  accounts:
    -
      id: account_1
      account_id: 6344615
      pass_phrase: KernighanRitchie1978
      secret_key: GFs6Ab44nC1pzJMeszQfEymnZ6hUeC
      deposit_account:
        usd: U6953052
      withdrawal_account:
        usd: U6953052